# Generated by Django 5.0.7 on 2024-08-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rasm',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
