# Generated by Django 5.0.7 on 2024-09-02 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0002_product_rasm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rasm',
            field=models.ImageField(default='no_image.webp', upload_to=''),
        ),
    ]
