# Generated by Django 5.0.7 on 2024-09-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='photo',
            field=models.ImageField(default='user.webp', upload_to='user/'),
        ),
    ]
