# Generated by Django 5.0.7 on 2024-09-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0005_alter_myuser_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='photo',
            field=models.ImageField(default='i(1).webp', upload_to='user/'),
        ),
    ]
