# Generated by Django 5.0.7 on 2024-09-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0006_alter_myuser_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='photo',
            field=models.ImageField(default='33.png', upload_to='user/'),
        ),
    ]
